### ISSUE TITLE
`for` loop support

### ISSUE THREAD

**Issue by rafalcieslak** [rafalcieslak/CCoscope#1]
This should be straightforward. You will need to add the `for` keyword to the lexer grammar, a new class representing `for` expressions in the AST, a grammar rule that will build the AST node instance when the keyword is spotted, and a codegen rule, which will be similar to `if` and `while` statements.

**Comment by socumbersome** [comment]
I tinkered a bit with it and decided to reuse `WhileExprAST::codegen` as a helper.
The implementation is buggy now though, so I created a new branch (5e42b84b1c4b59ca2d75c9808013a390b03171a0).
When trying to compile `examples/forloop1.cco` we get enigmatic:

Parsing ../examples/forloop1.cco
Found 0 prototypes and 1 function definitions. 
CCoscope: /home/ja/llvm/src/lib/IR/Constants.cpp:2040: static llvm::Constant\* llvm::ConstantExpr::getGetElementPtr(llvm::Type_, llvm::Constant_, llvm::ArrayRefllvm::Value*, bool, llvm::Type*): Assertion `Ty == cast<PointerType>(C->getType()->getScalarType())->getContainedType(0u)' failed.

I don't know whether it's a clang 3.x vs 3.y issue or I screwed up something :P

**UPDATE**
As problems seem not to be related to `for` loop implementation, I merge `forLoop` branch with master.
