### ISSUE TITLE
Colourful output

### ISSUE THREAD

**Issue by rafalcieslak** [rafalcieslak/CCoscope#14]
Colouring the output messages should be simple, and will immediately make our compiler superior to gcc, as it is the only difference most programmers see between gcc and clang.

**Comment by socumbersome** [comment]
Thumbs up :D

**Comment by socumbersome** [comment]
I believe it's closed now after 45361d1e306a1d7486f6a31e29b737a3acc9c99b ?

**Comment by rafalcieslak** [comment]
We have some basic mechanisms for controlling colours. The output is not yet as pretty as I would like it to be, but we can improve it separately, and consider this task done.
