### ISSUE TITLE
Inserting file location information into the AST

### ISSUE THREAD

**Issue by rafalcieslak** [rafalcieslak/CCoscope#23]
Each node in the AST should know what is the position in the source file that originated the expression associated with the AST. This is necessary for displaying line/column information alongside error messages.

**Comment by socumbersome** [comment]
Don't know why haven't this happened automatically, but after merge (https://github.com/rafalcieslak/CCoscope/commit/d323a72ca3fac2023af5638dd63d5d8e94b42032), this issue is closed.

**Comment by rafalcieslak** [comment]
That probably happened because github monitors phrases like "fixes #23" or "closes #23" in commit messages and pull requests, and as soon as it sees one (even if it's not in a relevant branch), it performs mentioned action. I find this feature profoundly dumb, but people generally like it (saves so much time!), and it is not possible to disable it.
