### ISSUE TITLE
Linking vs standard library of non-C functions

### ISSUE THREAD

**Issue by socumbersome** [rafalcieslak/CCoscope#26]
As of https://github.com/rafalcieslak/CCoscope/commit/a34d6cd99d2fd7a67553d180f0be4e88de1d75f9 , I broke the `gcd` example, because when we try to compile and link `examples/gcd.cco` and `examples/gcd_main.cco`, we have multiple definitions of `newComplex` functions (which I consider a standard-library function for our compiler, but it's not as low level as things in `libcco` to put it there). The problem is that I create this function in `CodegenContext::PrepareStdFunctionPrototypes` and, well, when we compile more than one file, multiple definitions will certainly appear.
The question is: what would be the best place to put this creation of `newComplex`? It seems to me that during compilation of "normal" files, we should emit just the prototype (in each of them), and then build a file with all the standard functions (currently only `newComplex` but I think there will be more in the future?) codegenned there, and link all those files up.
Do you agree?

And a kind of related question -- why can't we emit IR code when we compile more than one file? I hope it's just an artificial obstacle, because if we decide to have this standard library, then we will always link at least two files and it shouldn't hinder us from peeking at IR.

**Comment by rafalcieslak** [comment]
I believe the right place to place `newComplex` runtime implementation is exactly the `libcco`, and that it is precisely the purpose of the runtime library. We'll need to figure out how to link functions that use custom types in an elegant manner (I hope to do some experiments soon), but besides that, this is exactly why we needed `libcco` in the first place :-)

The limit for emitting IR when compiling multiple files is not a limit as in `not possible` but as in `not implemented yet`. The only issue is determining output file names, as the `-o` flag only specifies one name. Note that this won't be a problem when linking with an external library, as long as the library comes pre-compiled - and it wouldn't make much sense to compile such library each time the compiler is run.

**Comment by socumbersome** [comment]
After merging https://github.com/rafalcieslak/CCoscope/pull/33, this is now closed.
