### ISSUE TITLE
Basic types support

### ISSUE THREAD

**Issue by rafalcieslak** [rafalcieslak/CCoscope#4]
At the very least, type system should support:
- Attaching a type (as we see it) to each value and variable
- Recognizing types of literals (0, false, 0.0)
- Recognizing the type of the return value from a function
- Checking whether argument types for a function call match (no function overloading yet)

Things that may be implemented later:
- Overloaded operators and resolution
- Type conversions

**Comment by socumbersome** [comment]
I'm not sure whether my comment is appropriate to this issue, but: I think we should get rid of `enums` as types and switch to using classes from `typechecking.h` -- it's more extensible.

**Comment by rafalcieslak** [comment]
I suppose we can close this issue?

**Comment by socumbersome** [comment]
Well, maybe let's wait until we merge master with https://github.com/rafalcieslak/CCoscope/pull/20 .

**Comment by socumbersome** [comment]
Finally merged ( https://github.com/rafalcieslak/CCoscope/commit/985aecc2bcab293878fda87260180e85681c8802 ), so I close this issue.
