### ISSUE TITLE
float vs double

### ISSUE THREAD

**Issue by socumbersome** [rafalcieslak/CCoscope#7]
I think we should decide whether we want `float` or `double` datatype in our language -- there is a discrepancy between `lexer.lex` file and the rest of the compiler.

**Comment by rafalcieslak** [comment]
I don't think that this choice matters much at this stage of development. How about we call it a `floating type` and use `#define float_type double` for storing values of that type? This way it can be easily corrected if we find some reason for not using doubles.

**Comment by socumbersome** [comment]
If we want to conquer the world then I think we should support both `floats` and `doubles` :)
