### ISSUE TITLE
Unable to define function in tree.h due to grammar.m

### ISSUE THREAD

**Issue by socumbersome** [rafalcieslak/CCoscope#9]
When trying to define any function in `tree.h` file, e.g. `int foo(int x) { return x+1; }`, during compilation, we get errors -- in this case, it reads:

> CMakeFiles/CCoscope.dir/tokenizer.cpp.o: In function `foo(int)':
> /home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: multiple definition of`foo(int)'
> CMakeFiles/CCoscope.dir/compiler.cpp.o:/home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: first defined here
> CMakeFiles/CCoscope.dir/tree.cpp.o: In function `foo(int)':
> /home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: multiple definition of`foo(int)'
> CMakeFiles/CCoscope.dir/compiler.cpp.o:/home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: first defined here
> CMakeFiles/CCoscope.dir/lexer.cpp.o: In function `foo(int)':
> /home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: multiple definition of`foo(int)'
> CMakeFiles/CCoscope.dir/compiler.cpp.o:/home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: first defined here
> CMakeFiles/CCoscope.dir/token.cpp.o: In function `std::iterator_traits<std::_List_const_iterator<int> >::iterator_category std::__iterator_category<std::_List_const_iterator<int> >(std::_List_const_iterator<int> const&)':
> /home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: multiple definition of`foo(int)'
> CMakeFiles/CCoscope.dir/compiler.cpp.o:/home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: first defined here
> CMakeFiles/CCoscope.dir/parser.cpp.o: In function `foo(int)':
> /home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: multiple definition of`foo(int)'
> CMakeFiles/CCoscope.dir/compiler.cpp.o:/home/ja/Studies/7sem/cc/project/CCoscope/src/tree.h:38: first defined here
> CMakeFiles/CCoscope.dir/utils.cpp.o: In function `GetTmpFile(std::string)':
> /home/ja/Studies/7sem/cc/project/CCoscope/src/utils.cpp:19: warning: the use of`tmpnam' is dangerous, better use `mkstemp'
> collect2: error: ld returned 1 exit status
> make[2]: **\* [src/CCoscope] Błąd 1
> make[1]: **\* [src/CMakeFiles/CCoscope.dir/all] Błąd 2
> make: **\* [all] Błąd 2

Naturally, I don't really need this particular `foo` function, but it just serves as an example.

**Comment by rafalcieslak** [comment]
You clearly can't do that - `tree.h` is included by multiple translation units, and therefore such function would get compiled twice, resulting in linker confusion.

Why would you need to add functions to that header file? Just place it in `tree.c`. If you really need to have it in the header file, you can mark such function using `inline` keyword, this way it will be never compiled as a standalone function - it be always inlined, so the linker won't even see it.

**Comment by socumbersome** [comment]
Right, that was stupid -- I must have forgotten why there are header files at all :P
